[[redirects]]
  from = "/reservas"
  to = "/#reserva"
  status = 301
  force = true

[[redirects]]
  from = "/reservas/*"
  to = "/#reserva"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/stock-disponible-a-la-venta"
  to = "/#fleet"
  status = 301
  force = true

[[redirects]]
  from = "/nuestra-colección-exclusiva"
  to = "/#fleet"
  status = 301
  force = true

[[redirects]]
  from = "/nuestra-colección-exclusiva/*"
  to = "/#fleet"
  status = 301
  force = true

